/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafica;

import Dominio.Productor;
import Persistencia.ProductorDAO;
import com.mycompany.capalogica.FachadaLogica;
import com.mycompany.capalogica.ILogica;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hoshi
 */
public class FrmLoginProductores extends javax.swing.JFrame {

    private ILogica log;
    Productor p = new Productor();
    
    public FrmLoginProductores() {
        initComponents();
        log=new FachadaLogica();
    }
    
    public void ingresarProductor() {
        if (log.verificarProductor(txtNombreProductor.getText(), Integer.parseInt(txtNumIdentificador.getText()))) {
            
//                PersonaDAO personaDAO = new PersonaDAO();
//                //PONER TXT.GETTEXT DENTRO DE DONDE ESTAN LAS COMILLAS AHORITA LISTO
//
//                List<Persona> persona = personaDAO.buscarRfc(lblRfc.getText());
//
//                
//                    JOptionPane.showMessageDialog(this, "Se encontro el rfc");
//                    this.setVisible(false);
//                    FrHistorialLicencia historial = new FrHistorialLicencia(persona.get(0));
//                    historial.setVisible(true);
//                    this.dispose();
            ProductorDAO productorDAO = new ProductorDAO();
            List<Productor> productores = productorDAO.buscarNumeroEmpresa(Integer.parseInt(txtNumIdentificador.getText()));
            
            this.setVisible(false);
            FrmMenuPrincipal menu = new FrmMenuPrincipal(productores.get(0));
            menu.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o número inválido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblPregunta = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIdentificadorProductor = new javax.swing.JLabel();
        lblNombreProductor = new javax.swing.JLabel();
        txtNumIdentificador = new javax.swing.JTextField();
        txtNombreProductor = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPregunta.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblPregunta.setText("¿No esta registrado el productor?");
        jPanel3.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        btnRegistro.setText("Click Aquí");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 360, 150));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdentificadorProductor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIdentificadorProductor.setText("Número identificador");
        jPanel2.add(lblIdentificadorProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblNombreProductor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNombreProductor.setText("Nombre productor");
        jPanel2.add(lblNombreProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtNumIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIdentificadorActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 190, 30));
        jPanel2.add(txtNombreProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 190, 30));

        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 770, 190));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblTitulo.setText("PRODUCTOR SOLICITANTE");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginproyectod.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdentificadorActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmRegistroProductores registro = new FrmRegistroProductores();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        this.ingresarProductor();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginProductores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblIdentificadorProductor;
    private javax.swing.JLabel lblNombreProductor;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNombreProductor;
    private javax.swing.JTextField txtNumIdentificador;
    // End of variables declaration//GEN-END:variables
}
